import Head from "next/head";
import App from "./App";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind, NextJS Demo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <App />
    </div>
  );
}
